### ISSUE TITLE
Updating state flow using context.flow is not recognized

### ISSUE THREAD

**Issue by kinanajoudeh** [felangel/flow_builder#24]
When I try to update the flow state via context.flow<T>().update it gives an error:

Error: The method 'flow' isn't defined for the class 'BuildContext'.
 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
 ('../../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'flow'.

**Comment by felangel** [comment]
Hi @kinanajoudeh 👋 
Thanks for opening an issue!

I believe you are missing the flow_builder import:

```dart
import 'package:flow_builder/flow_builder.dart';
```

Hope that helps 👍
