### ISSUE TITLE
Is it possible to add page transition animation to FlowBuilder?

### ISSUE THREAD

**Issue by e200** [felangel/flow_builder#29]
**Is your feature request related to a problem? Please describe.**
Same as title.

**Describe the solution you'd like**
Would be nice to have page transition animations like we have when using `Navigator`'s methods.

**Describe alternatives you've considered**
We could provide a `MaterialPageRoute` or equivalent in place of `MaterialPage`.

**Comment by felangel** [comment]
Hi @e200 👋 
Thanks for opening an issue!

You can definitely use custom `PageTransitions` with `FlowBuilder` 👍 

```dart
class MyPage<T> extends Page<T> {
  const MyPage({required this.child, LocalKey? key}) : super(key: key);

  final Widget child;

  @override
  Route<T> createRoute(BuildContext context) {
    return PageRouteBuilder(
      transitionDuration: const Duration(seconds: 1),
      settings: this,
      pageBuilder: (
        BuildContext context,
        Animation<double> animation,
        Animation<double> secondaryAnimation,
      ) {
        return ScaleTransition(scale: animation, child: child);
      },
    );
  }
}
```

Then you can use your custom `Page` instead of `MaterialPage`:

```dart
return FlowBuilder<MyFlowState>(
      state: FlowState.initial,
      onGeneratePages: (state, pages) {
        // We can use `MyPage` with our custom transition animation :)
        return [MyPage(child: MyWidget())];
      },
    );
```

Let me know if that helps! 👍

**Comment by e200** [comment]
It works! Many thanks @felangel.
