### ISSUE TITLE
Support for OpenContainer from animations package

### ISSUE THREAD

**Issue by amitkot** [felangel/flow_builder#46]
**Is your feature request related to a problem? Please describe.**
Using this package the routing is triggered by changes to the state. 
How would you suggest integrating it with a widget such as `OpenContainer` where the routing is triggered imperatively?

**Comment by felangel** [comment]
Hi @amitkot 👋 
Thanks for opening an issue!

Can you please provide a minimal reproduction sample which illustrates the issue you're facing? It will be much easier to help, thanks! 🙏

**Comment by felangel** [comment]
Closing for now since there is no reproduction sample. Feel free to provide one and I'm happy to take a look 👍
