### ISSUE TITLE
[Feature Request] `FlowController<T>` should implement `ValueListenable<T>` instead of `Listenable`

### ISSUE THREAD

**Issue by narcodico** [felangel/flow_builder#66]
**Is your feature request related to a problem? Please describe.**
Currently `flow_builder` can't be used to build widgets. Although `flow_builder`'s responsibility is building the navigation stack, users could also benefit from being able to use `ValueListenableBuilder` with a `FlowController`.

**Describe the solution you'd like**
`FlowController<T>` should implement `ValueListenable<T>` instead of `Listenable`.
The only downside is this would force `FlowController` to override `ValueListenable`'s `value`. Right now the value's role is played by the `state` property. Couple of options to overcome this:
- override value with:
```
@override
T get value => _notifier.value;
```
and leave the rest of the implementation as it is. Weird solution to say the least, but I guess it's the only way to keep the `state` naming 🙄
- override value with:
```
@override
T get value => _notifier.value;
```
and deprecate `state` for the next release; we could then remove `state` and keep `value` to better align with flutter naming conventions. I'd prefer this route.

If you like this change I'm willing to open a PR.

**Comment by felangel** [comment]
@narcodico thanks for opening an issue!

There have been some recent changes to refactor `FlowController` to extend `ChangeNotifier` rather than to implement `Listenable` (see #61). As a result, you should be able to use an `AnimatedBuilder` with the `FlowController` to rebuild some UI based on the state (available in flow_builder v0.0.5).

Let me know what you think, thanks!

**Comment by narcodico** [comment]
@felangel that will also do the job! 👍

**Comment by felangel** [comment]
Awesome, closing for now but let me know if you have any additional feedback/suggestions and I'm happy to reopen this 👍
